### ISSUE TITLE
中国地图少了南海

### ISSUE THREAD

**Issue by ECNUJason** [nelsonkuang/ant-admin#1]
ant-admin/src/components/charts/D3SimpleChinaMapChart.js

**Comment by peterpanBest** [comment]
http://www.iampua.com/pui/ant-admin.html#/simple-china-map-chart

中国地图少了南中国海，建议暂时把这个组件去掉。

**Comment by yoyo837** [comment]
我能说还少了藏南地区吗？

**Comment by nelsonkuang** [comment]
好的，今天看看

**Comment by nelsonkuang** [comment]
> ant-admin/src/components/charts/D3SimpleChinaMapChart.js

已经修改了geojson文件了，增加了南中国海了

**Comment by nelsonkuang** [comment]
> 我能说还少了藏南地区吗？

已经修改了geojson文件了，增加了南中国海了
