### ISSUE TITLE
项目遇到transition相关的都报错了

### ISSUE THREAD

**Issue by k-kaikai** [nelsonkuang/ant-admin#3]
具体内容显示transition已经不是一个函数了，不知道是因为版本原因还是其他原因，求解

**Comment by nelsonkuang** [comment]
> 具体内容显示transition已经不是一个函数了，不知道是因为版本原因还是其他原因，求解

这是D3V4的版本，最新版D3V5 API已经有所变化，如果你用最新版建议自己看看API了解使用方法。最近较忙没时间更新哈，不好意思
